### ISSUE TITLE
Installing risan oauth library through composer getting error

### ISSUE THREAD

**Issue by jyotiraghav93** [risan/oauth1#16]
i am getting below error while  risan oauth library through composer ,

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package risan/oauth1 No version set (parsed as 1.0.0) is satisfiable by risan/oauth1[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

Please suggest what I am missing?

**Comment by risan** [comment]
Sorry for the late response. Try adding the `minimum-stability` and `prefer-stable` properties to your `composer.json` like so:

```
{
    "require": {
        ...
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Hope that would work.
