### ISSUE TITLE
YOUR_AUDIOMACK_KEY?

### ISSUE THREAD

**Issue by daslicht** [risan/oauth1#19]
where to get theses ? 

```
   'client_credentials_identifier' => 'YOUR_AUDIOMACK_KEY',
    'client_credentials_secret'     => 'YOUR_AUDIOMACK_SECRET',
```
~Marc

**Comment by Philipp91** [comment]
How to get these keys is provider-specific, i.e. in this case you need to enquire with Audiomack or just read their documentation very closely.

**Comment by daslicht** [comment]
I haven't found anything in their docs, that's why i ask here, and I thought this repo was related to audiomack(was in a hurry).
